export const years = [
  { name: "2021" },
  { name: "2020" },
  { name: "2019" },
  { name: "2018" },
  { name: "2017" },
  { name: "2016" },
  { name: "2015" },
  { name: "2014" },
  { name: "2013" },
  { name: "2012" },
  { name: "2011" },
  { name: "2010" },
  { name: "2009" },
  { name: "2008" },
  { name: "2007" },
  { name: "2006" },
  { name: "2005" },
  { name: "2004" },
  { name: "2003" },
  { name: "2002" },
  { name: "2001" },
  { name: "2000" },
  { name: "1999" },
  { name: "1998" },
  { name: "1997" },
  { name: "1996" },
  { name: "1995" },
  { name: "1994" },
  { name: "1993" },
  { name: "1992" },
  { name: "1991" },
  { name: "1990" },
  { name: "1989" },
  { name: "1988" },
  { name: "1987" },
  { name: "1986" },
  { name: "1985" },
  { name: "1984" },
  { name: "1983" },
  { name: "1982" },
  { name: "1981" },
];

export const makes = [
  { name: "Acura" },
  { name: "Alfa Romeo" },
  { name: "Aston Martin" },
  { name: "Audi" },
  { name: "Bentley" },
  { name: "BMW" },
  { name: "Bugatti" },
  { name: "Buick" },
  { name: "Cadillac" },
  { name: "Chevrolet" },
  { name: "Chrysler" },
  { name: "Dodge" },
  { name: "Ferrari" },
  { name: "Fiat" },
  { name: "Ford" },
  { name: "Genesis" },
  { name: "GMC" },
  { name: "Honda" },
  { name: "Hyundai" },
  { name: "Infiniti" },
  { name: "Jaguar" },
  { name: "Jeep" },
  { name: "Kia" },
  { name: "Lamborghini" },
  { name: "Land Rover" },
  { name: "Lexus" },
  { name: "Lincoln" },
  { name: "Lotus" },
  { name: "Maserati" },
  { name: "Mazda" },
  { name: "McLaren" },
  { name: "Mercedes-Benz" },
  { name: "Mini" },
  { name: "Mitsubishi" },
  { name: "Nissan" },
  { name: "Polestar" },
  { name: "Porsche" },
  { name: "Ram" },
  { name: "Rolls-Royce" },
  { name: "Scion" },
  { name: "Smart" },
  { name: "Subaru" },
  { name: "Tesla" },
  { name: "Toyota" },
  { name: "Volkswagen" },
  { name: "Volvo" },
];

export const colors = [
  { name: "Black" },
  { name: "Blue" },
  { name: "Brown" },
  { name: "Gold" },
  { name: "Gray" },
  { name: "Green" },
  { name: "Orange" },
  { name: "Pink" },
  { name: "Purple" },
  { name: "Red" },
  { name: "Silver" },
  { name: "White" },
  { name: "Yellow" },
];
